### ISSUE TITLE
Punching trees doesn't hurt

### ISSUE THREAD

**Issue by Nincodedo** [UndeadZeratul/ThereWillBeBlood#159] opened 2016-09-25 06:08 UTC

**Comment by UndeadZeratul** [comment] 2016-09-28 15:01
According to [this](https://github.com/einsteinsci/betterbeginnings/wiki/Block-Breaking#stuck), it seems that because I'm on peaceful in the earliest stage of my LP, I don't get hurt from this mechanic; marking this "as intended" and closing

**Closed as completed by UndeadZeratul** 2016-09-28 15:01 UTC
Labels: Bug, As Intended

**Comment by Roshag** [comment] 2017-06-30 14:08
Nope, there is a bug with Natura trees. I'm sure of Amaranth wood
